security:
  # No usamos enable_authenticator_manager, ya que generó un error
  
  password_hashers:
    App\Entity\Usuario: 'auto'  # Versión simplificada sin 'algorithm'
  
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Usuario
        property: email
  
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    
    login:
      pattern: ^/api/login
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~
    
    main:
      lazy: true
      provider: app_user_provider
  
  access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Usamos IS_AUTHENTICATED_ANONYMOUSLY en lugar de PUBLIC_ACCESS
    - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }